name: Validate Pull Request

# Run when a pull request is generated for one of the specified branch.
# Runs on the pull request branch.
on:
  pull_request:
    branches: ["main"]

jobs:
  merge-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - name: Install node dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
